openapi: 3.0.0
info:
  title: Library API
  version: 1.0.0
servers:
  - url: http://localhost:5000

paths:
  /books:
    get:
      summary: Get all books
      responses:
        '200':
          description: Successful response with list of all books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Add book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookInput'
      responses:
        '201':
          description: Book added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

  /books/{bookId}:
    get:
      summary: Get book by ID
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response with information about book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found

    put:
      summary: Update book information
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookInput'
      responses:
        '200':
          description: Book information updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found

    delete:
      summary: Delete book by ID
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Book deleted
        '404':
          description: Book not found

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
          example: "12345"
        title:
          type: string
          example: "War and Peace"
        author:
          type: string
          example: "L.N. Tolstoy"
        genre:
          type: string
          example: "Novel"
        year:
          type: integer
          example: 1869
    BookInput:
      type: object
      properties:
        title:
          type: string
        author:
          type: string
        genre:
          type: string
        year:
          type: integer
