global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['flask-app:5000']
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]